# Shared default configuration
spring:
  profiles:
    active: default
  
  # Common database configuration
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  # JPA common configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  # Flyway common configuration
  flyway:
    enabled: true
    locations: classpath:/db/migration
    baseline-on-migrate: true
    baseline-version: 0
    validate-migration-naming: true

# Eureka common configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

# Actuator common configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,configprops,metrics
  endpoint:
    health:
      show-details: when-authorized
  info:
    env:
      enabled: true

# Logging configuration
logging:
  level:
    com.example: INFO
    org.springframework.cloud: WARN
    org.springframework.web: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Feature toggles
feature:
  enable-swagger: true
  enable-actuator: true
