
spring:
  application:
    name: DEPARTMENT-SERVICE
  
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456!
    hikari:
      pool-name: DepartmentServicePool

  jpa:
    properties:
      hibernate:
        default_schema: department

  flyway:
    schemas: department
    default-schema: department
    table: flyway_schema_history_departments
    create-schemas: true

server:
  port: 8082


department:
  service:
    
    pagination:
      default-page-size: 20
      max-page-size: 100
    
    
    cache:
      enabled: true
      ttl: 600 
    
    
    business:
      allow-delete-with-employees: false
      max-name-length: 100
      max-description-length: 500


logging:
  level:
    com.example.department: DEBUG


feature:
  enable-employee-count: true
  enable-protective-delete: true
