# Employee Service specific configuration
spring:
  application:
    name: EMPLOYEE-SERVICE
  
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456!
    hikari:
      pool-name: EmployeeServicePool

  jpa:
    properties:
      hibernate:
        default_schema: employee

  flyway:
    schemas: employee
    default-schema: employee
    table: flyway_schema_history_employees
    create-schemas: true

server:
  port: 8081


employee:
  service:
    
    pagination:
      default-page-size: 20
      max-page-size: 100
    
    
    cache:
      enabled: true
      ttl: 300 # 5 minutes
    
    
    business:
      max-allocation-percent: 100
      default-allocation-percent: 50


logging:
  level:
    com.example.employee: DEBUG
    org.springframework.cloud.openfeign: DEBUG



feature:
  enable-department-enrichment: true
  enable-bulk-operations: true

management:
  endpoints:
    web:
      exposure:
        include: refresh,env,loggers,health,info
