spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          # Use local file system as configuration repository
          uri: file://${user.dir}/config-repo
          # If using Git repository, configure like this:
          # uri: https://github.com/your-username/your-config-repo.git
          # default-label: main
        # Support local file system
        native:
          search-locations: classpath:/config-repo
      # Allow all configurations
      allow-override: true
      override-none: true

server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,configprops
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.config: DEBUG
